name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: |
          sudo apt install -y git curl
          yarn --frozen-lockfile

      - name: Run lint and stylelint project
        run: |
          yarn lint
          yarn stylelint

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test
